### ISSUE TITLE
Display if user has active buff

### ISSUE THREAD

**Issue by phillipthelen** [HabitRPG/habitica-ios#107]
Display if the own user and party members have active buffs

**Comment by phillipthelen** [comment]
@saraolson since we now have the member list on the party screen, should we use the icon/design for buffs from that?

![screen shot 2018-07-03 at 16 27 53](https://user-images.githubusercontent.com/298062/42225971-17085b98-7ede-11e8-9e29-a2f4df22ee78.png)

For the header, I would position the icon after the "lvl 12 warrior" text instead of right aligned.

**Comment by saraolson** [comment]
yeah that sounds good to me, tested it in mockups and it looked like it had enough space but double check when you put it into code. since the 'level X job' line is more controlled than the name line it should work fine.
