### ISSUE TITLE
Empty Checklist Box

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica-ios#116]
Similar to https://github.com/HabitRPG/habitrpg-ios/issues/78, but without a crash.

In the most recent build (63), empty checklist boxes that are not associated with any task appeared after I checked off a To-Do. Refreshing fixed the problem.
![img_3198](https://cloud.githubusercontent.com/assets/3494081/8663736/50386c0e-2983-11e5-97f9-aaaa98810d9a.PNG)

**Comment by lemoness** [comment]
Encountered this again: 

![img_3676](https://cloud.githubusercontent.com/assets/3494081/10477677/f65bcf46-720c-11e5-9c8a-9b6192b9419c.PNG)
![img_3677](https://cloud.githubusercontent.com/assets/3494081/10477676/f659e05a-720c-11e5-90d3-bf18f087ef90.PNG)

**Comment by vIiRuS** [comment]
Can't seem to reproduce it. Are there steps you can do to reproduce the error?

**Comment by lemoness** [comment]
Not that I have found - it happens infrequently. The next time it occurs I
will report exactly what I was doing.

**Comment by lemoness** [comment]
It occurred again. Here's what happened:

I opened the app.
I filtered for Dated To-Dos.
I opened a To-Do with a checklist and checked off one of the items.
I tapped the To-Do to edit it and changed the due date.
I hit Save.
The empty checklist boxes appeared. 

I've tried to replicate this with other To-Dos, but it had no effect.

**Comment by vIiRuS** [comment]
Is it possible that you didn't tap the todo to edit but instead a checklist item? I believe that could cause this behaviour.

**Comment by lemoness** [comment]
It's possible I may have missed! Will check.
