### ISSUE TITLE
Empty state for task lists

### ISSUE THREAD

**Issue by kyle-fox** [HabitRPG/habitica-ios#132]
This would be especially useful when searching and switching between tabs that are sharing the search term. If the user is searching for something in one tab, and then changes to another where there aren't any results, they will see a blank screen, which can be a little jarring.

I can implement something using [DZNEmptyDataSet](https://github.com/dzenbot/DZNEmptyDataSet) quickly, but I wanted your input before doing so. A designer could have some fun with it too, so it wouldn't just be text!

**Comment by vIiRuS** [comment]
With the current class structure, every tableviewcontroller in the app would have to extend the controller of the library. Not sure if that would be a problem or not. I'll take a closer look at the library tomorrow but it probably is a good idea to use it.

**Comment by kyle-fox** [comment]
My plan was to just have to conform to the delegate and datasource once in [`HRPGTableViewController.h`](https://github.com/HabitRPG/habitrpg-ios/blob/master/HabitRPG/TableViewController/Tasks/HRPGTableViewController.h) since it is the parent of the three tableViews for habit, daily, and todo - similar to searching. Then what it shows can be conditional based on the `typeName` or if the user is searching. I *think* that should work!

**Comment by vIiRuS** [comment]
I misread the  readme. I thought inread it had to be subclassed and not use a delegate/datasource. Sorry. In that case i don't see a reason against it.

**Comment by vIiRuS** [comment]
@kyle-fox Are you working on this? Otherwise I would go ahead and implement it.

**Comment by kyle-fox** [comment]
I am not - I didn't know what you wanted to do for that placeholder, so it might be best that you go ahead and implement it. I think it would be great to have an image with something cool as the placeholder, but that would mean getting a designer involved.

**Comment by saraolson** [comment]
So we do have designs for empty states now, just a simple icon and explanation of the category on a blank screen (similar to what web now has implemented). So if someone wants to pick this up, they're there.
