### ISSUE TITLE
Text field content doesn't move with cursor for long checklist items

### ISSUE THREAD

**Issue by AnitaYCheng** [HabitRPG/habitica-ios#135]
If you have a long checklist item, the cursor stops at the end of the visible text field and doesn't continue as you type. It seems as if there's a max character limit, but if you hold and drag the cursor to the right, the rest of the text shows up. So it works, but it makes it hard to see what I'm typing.

**Comment by vIiRuS** [comment]
This might be a bug in [XLForm](https://github.com/xmartlabs/XLForm).
