### ISSUE TITLE
iOS app allows editing of challenge task

### ISSUE THREAD

**Issue by rslee0** [HabitRPG/habitica-ios#187]
Not sure whether this is an issue with the iOS app or the webapp, but the behavior is inconsistent... I have one habit that is part of a challenge; I cannot edit its attributes (pos/neg, difficulty) on the web app, but I just modified them on the iOS app. The changes showed up in the web app when I synced it, and I am still unable to make changes to the attributes there.

**Comment by KeyboardCowboy** [comment]
Please let me know if this should be split into a separate issue, but challenge-based dailies are also editable and deletable (with a left swipe) from the iOS app, but not from the web app.

We tested this last night and the nightly reset does not bring them back.  My assumption would be that any items from a Challenge would be locked and thereby not editable or deletable.

**Comment by crookedneighbor** [comment]
This is an api problem (though the ios app will need to be adjusted to not have a ui that lets you do this)
