### ISSUE TITLE
[v 1.1 (70)] Checklist items sometimes do not display

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica-ios#192]

**Comment by lemoness** [comment]
This only seems to affect Dailies.

Closing and reopening the checklist causes different items to disappear
![img_3507](https://cloud.githubusercontent.com/assets/3494081/9886937/de88ce18-5ba1-11e5-8b99-d8ebbd62db2a.jpg)
![img_3506](https://cloud.githubusercontent.com/assets/3494081/9886938/de92717a-5ba1-11e5-9f67-188074fa5999.jpg)

**Comment by lemoness** [comment]
Further testing - this happens with all of my Dailies that have a checklist.

**Comment by lemoness** [comment]
Closing and reopening the app has fixed the problem. As I keep using the app throughout the day, I'll let you know if it happens again, and what I was doing that might have caused it.

**Comment by lemoness** [comment]
Unfortunately, this problem is back in v 1.1 (80).

**Comment by vIiRuS** [comment]
Does it still happen with all dailies? tried to reproduce it and they always display correctly for me.

**Comment by lemoness** [comment]
No longer happening in version 83!

**Comment by lemoness** [comment]
Noooo everyone's least favorite checklist bug is suddenly back for Dailies in Build 91.

**Comment by lemoness** [comment]
To-Dos seem fine.

**Comment by lemoness** [comment]
1) Closing and reopening the app improved things, but it did not completely fix the problem -- one of my Dailies is still exhibiting this checklist behavior.

2) Checking off a checklist item usually causes it to disappear.

**Comment by lemoness** [comment]
Note - I just went through and tested checklists in Dailies for version 90, and confirmed that they work normally, so it seems to have been reintroduced with v91.

**Comment by lemoness** [comment]
Another report of this:

Checklist items are sometimes showing up as blank in dailies.

"Not sure how to describe specific steps to reproduce, but I have a number of dailies with checklists. The number of items on the checklists vary from 4 to 10. Intermittently, one or more of the items on the checklist appear blank. The space for the item is there, but there is no content, not even boxes or colors, let alone specific content of the list. This has happened to a variety of my dailies and a variety of checklist items - in other words, it's not always the same items. I see the same behavior on my iPhone 6S Plus running the same version of Habitica and the same version of iOS. The problem was present in earlier versions of both Habitica and iOS.

I hope this enough info. Don't hesitate to contact me with questions."

iOS Version: 9.3.2
Device: iPad6,3
App Version: 1.3.1
User UUID: 554e493e-2be2-46f1-8391-c37245d1f30e

**Comment by ncolton** [comment]
iOS Version: 10.3.2 (14F89)
Device: iPhone 6S
App Version: 1.8.1 (198)

I see this happen for my dailies as well. For the dailies with only a few items (2, generally), it seems more rare than dailies with 5+ items. In my case, the 5+ item list, when I expand to see the individual checklist items, has more than five rows of items, some with proper rendering, others blank/empty. Which items are not rendered can sometimes swap if I expand other items, then go back and expand the one I am attempting to interact with.
