### ISSUE TITLE
[v 1.1 (79) iPad] Wrong experience and mana in user profile

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica-ios#236]
When viewing the profiles of people other than yourself, the Experience and Mana bars are empty, with a total XP and MP of 0.
![img_0024](https://cloud.githubusercontent.com/assets/3494081/10507694/19bb160c-72d7-11e5-9668-8cff5165a1a9.jpg)

**Comment by vIiRuS** [comment]
This is unfortunately more work/harder than I thought. The problem is with mana, as that is calculated according to the users gear. experience already work correctly now.
