### ISSUE TITLE
TUTORIAL [v 1.1 (80)] Reminder improvements

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica-ios#248]
So, in the user test, the user was not happy about the "Remind me tomorrow" and "Got it" interaction on every tab. We may want to get rid of that in favor of a single Justin at the very end that says "Phew! This is a lot of info. Do you want me to remind you later about all these features?"
"Remind me later today"
"Remind me tomorrow"
"Don't remind me"

**Comment by vIiRuS** [comment]
But we don't have an end. (Which is also part of the point) so we can't display something at the end.
Maybe instead have "remind me tomorrow" in an upper corner of the screen and have tapping anywhere ok the screen act as the "got it" button

**Comment by lemoness** [comment]
In this case, the "end" would be after the user has seen all of the options. A reminder in the corner is better than nothing, but I would have to see it to make sure it looks okay.
