### ISSUE TITLE
Add Support for dynamic text to more labels

### ISSUE THREAD

**Issue by phillipthelen** [HabitRPG/habitica-ios#286]
Some menus and the header do not scale the text at all.

**Comment by drougojrom** [comment]
I can fix, if you say which labels have that issue

**Comment by phillipthelen** [comment]
You can check which ones do not work properly by using the Accessibility Inspector with the iOS simulator. You can find that in in XCode menu under XCoder > Open Developer Tool > Accessibility Inspector.

**Comment by JKKross** [comment]
Is this issue still open? I'd like to give it a try!
