### ISSUE TITLE
can't unset date for todos

### ISSUE THREAD

**Issue by phillipthelen** [HabitRPG/habitica-ios#292]
When a date is set it can't be unset again.

**Comment by kyle-fox** [comment]
See #136, which seems to be closed without being resolved. The issue still exists in Restkit ignoring null values, as far as I know - @crookedneighbor's suggestion for changing the API to accept `false` as valid might be the best solution.

**Comment by Alys** [comment]
In https://github.com/HabitRPG/habitica/issues/8820 @paglias has said that fixing this in the iOS app's code might be better because changing the API to accept false might not work with Mongoose.
