### ISSUE TITLE
Party Tutorial can not dismiss, wrong avatar displayed

### ISSUE THREAD

**Issue by CodeMySky** [HabitRPG/habitica-ios#294]
The Purple Button shows every time when enter party.
![Purple Button shows every time](https://cloud.githubusercontent.com/assets/1545856/11415968/5fc3a012-93d7-11e5-9565-1b3a0b45a012.jpg)

If I click 2 members the purple button will not disappear. If I click that it will show tutorial in wrong context.
![Wrong tutorial](https://cloud.githubusercontent.com/assets/1545856/11416010/d0e41d26-93d7-11e5-9856-c2fa08558f78.jpg)

And if I click I got it. It will show a network error even my network is perfectly fine.
![Network Error](https://cloud.githubusercontent.com/assets/1545856/11416029/f809b51e-93d7-11e5-9b2e-12bade4eb581.jpg)

And the avatar of my friend should be the one shown on the web site instead of wearing nothing.
![Right Avatar](https://cloud.githubusercontent.com/assets/1545856/11416061/3331d96e-93d8-11e5-9e60-7739de6d768a.jpg)

**Comment by lemoness** [comment]
Thanks for reporting these issues! They are in fact two separate problems. For the Party Tutorial, we're investigating the cause, but in the meantime, it should disappear if you clear your cache under Menu > Settings. 

I've confirmed that some of the Armoire items do not show up properly in the small images for party members.
