### ISSUE TITLE
changing the Custom Day Start time can cause cron to run unexpectedly.

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-ios#296]
When the Custom Day Start time is changed in the iOS app, the user isn't given advanced warning of when their next cron will run, and the `lastCron` date isn't set to the current time (important to prevent an immediate cron under some circumstances).

The relevant code from the website is:
https://github.com/HabitRPG/habitrpg/blob/046e7bcfdc75d6e532027197bfe4380ec88abcd5/website/public/js/controllers/settingsCtrl.js#L224

https://github.com/HabitRPG/habitrpg/blob/590adb3438d3a30d9a820ec9094b1d56922fa1db/website/server/controllers/api-v3/user.js#L1310 (the API route for saving the new CDS time)

**Comment by Alys** [comment]
I've just edited the first post to replace the second link with a more relevant one (the API route for saving the CDS time).

**Comment by phillipthelen** [comment]
The text should be displayed in the settings as a footer below the CDS section.
