### ISSUE TITLE
When signing up default dailies can be shown as grey even if they are due

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica-ios#304]
It probably happens only when the account is created in some timezones at particular times

**Comment by NightSparkle** [comment]
Also happens to me. I'm using IPad 2 IOS 9.2 and my time zone is UTC-6:00. The desktop version doesn't seem affected, and if you set it back to 'yesterday', it apears fine in IOS. In android you can see like for tomorrow, (even thought in IOS and desktop you don't). When changing it in android to 'today', it doesn't affects the desktop version and the IOS version fixes
