### ISSUE TITLE
Blank Quests

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica-ios#311]
Reported on Twitter:

"Blank bar in Inventory that says I have 2 of something but it doesn't do anything. Any idea what it is? [Quitting and reopening didn't fix it.] Got another blank row now. Hard reset didn't fix it, either. Updating iOS didn't fix it either. Not a big problem but it's weird."
![cwd9cuawiaibdfj jpg-large](https://cloud.githubusercontent.com/assets/3494081/11911000/cf677fdc-a5bc-11e5-9dda-25c467d03e63.jpeg)
![cww6r2kxiaa-weq jpg-large](https://cloud.githubusercontent.com/assets/3494081/11911001/cf739c0e-a5bc-11e5-87f2-6aa70fa058c9.jpeg)

**Comment by josephholsten** [comment]
I'm also seeing this.

**Comment by OverMyColdCoffee** [comment]
I'm getting duplicate potions, as well. Just the ones from drops, though. The Peppermint Potion I bought from the Seasonal Shop is only there the once. The desktop page tells me I have 2 Desert Potions and 1 Skeleton Potion but the iOS app tells me I have double that. I don't mean the numbers are different I mean it lists each thing twice on separate rows. They are visible, though (unlike the quests).


![desktop screenshot](https://cloud.githubusercontent.com/assets/16674832/12278786/eb0d5852-b97a-11e5-964e-7761cbfedfb7.png)

![app screenshot](https://cloud.githubusercontent.com/assets/16674832/12278866/776f9cba-b97b-11e5-8fc0-b976f92dbf91.PNG)

**Comment by vIiRuS** [comment]
I have a workaround for this bug, and would need users that experience this to verify that it works. @josephholsten @OverMyColdCoffee If you would like to (temporarily) join the beta test for the app, could you write me an email to mobile@habitica.com with you apple-id email address?

**Comment by josephholsten** [comment]
@vIiRuS sorry about that, I haven't been using Habitica in a while. Thanks for following up. Always be closing tickets!
