### ISSUE TITLE
"Back" in equipment views translated as the action

### ISSUE THREAD

**Issue by vIiRuS** [HabitRPG/habitica-ios#315]

**Comment by a-ayyash** [comment]
Some more description here would be great. 

I went inside the equipment view and pressed the back button ( labeled Menu ) and it seemed fine. 

I went inside one of the equipments "Head" and pushed the back button (labeled Equipment) and made sure the head wasn't equipped. 

I noticed that equipping a Head didn't update my avatar though. is this relevant ?

**Comment by vIiRuS** [comment]
The problem is that the string "Back" is translated as the action in "to go back". Even if it is in p.e.the equipment overview, where it should be translated as the body part.

**Comment by greatghoul** [comment]
![image](https://cloud.githubusercontent.com/assets/208966/21581256/d61529dc-d064-11e6-9428-2d7704c336f1.png)

Then translation in Simplified Chinese is still incorrect.

it should be `后背` or `背部` as  the body part, but not `返回` as an action.

**Comment by Alys** [comment]
@greatghoul Thank you! I've copied your report to the [Aspiring Linguists of Habitica](https://habitica.com/#/options/groups/guilds/7732f64c-33ee-4cce-873c-fc28f147a6f7) guild.  If you'd like to help with translations, you'd be most welcome to! Drop in to that guild to see the resources in the guild's description and to chat to other translators.

**Comment by GitHubSphinx** [comment]
@vIiRuS is it only about `HabitRPG/Localizable.strings:English (en):plaintext:Back` or also about `HabitRPG/Base.lproj/Main.storyboard:English (en):plaintext:FYR-h9-UfW.normalTitle` and `HabitRPG/Base.lproj/Main.storyboard:English (en):plaintext:5AI-vM-jzp.normalTitle` too?
