### ISSUE TITLE
Suggestion: x-callback-url

### ISSUE THREAD

**Issue by librarianmage** [HabitRPG/habitica-ios#345]
**Note:** I put this here because I didn't know where else this should go (should I put this on the Trello board?)

From http://x-callback-url.com/:

> The goal of the x-callback-url specification is to provide a standardized means for iOS developers to expose and document the methods they make available to other apps. Using x-callback-url’s source apps can launch other apps passing data and context information, and also provide parameters instructing the target app to return data and control back to the source app after executing an action.

This might be useful for people who like using automation apps ([Workflow](https://workflow.is/), [Launch Center Pro](launchcenterpro.com)) as a way to allow them to automate Habitica. Any thoughts?

**Comment by vIiRuS** [comment]
No, this is the right place to suggest this.

This looks interesting. I'd like to have habitica be more compatible with other apps and automation things, so I'd be all for adding something like this.
I can't tell though when I would have time to implement something like this, so if anybody is interested in creating a PR, it would be more than welcome!
