### ISSUE TITLE
Header sometimes disappears

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica-ios#368]
Sometimes when navigating to choose a mount or an avatar customization, the header disappears. 
![slack_for_ios_upload png](https://cloud.githubusercontent.com/assets/3494081/14971151/81ef0f12-1084-11e6-8e83-2064db515bf9.jpeg)
![slack_for_ios_upload](https://cloud.githubusercontent.com/assets/3494081/14971152/81f179d2-1084-11e6-8b0a-81830a397404.jpg)

Because these screens involve a choice that changes the look of the avatar, the header should definitely be visible.

**Comment by saraolson** [comment]
Gonna keep this flagged for design to return to when we get the stable updates in

**Comment by saraolson** [comment]
While working through this, i felt that showing the full header was a lot of uneccesary noise when really just you want to see what your pet looks like. So I made a mockup with a bare-bones header that would be sticky so you can always see what your pet looks like without having to scroll up.

This kinda changes the meaning of the issue but will just attach this whenever we get to redoing stable.

<img width="391" alt="screen shot 2017-11-28 at 1 06 36 pm" src="https://user-images.githubusercontent.com/12453119/33336307-726fb1b2-d43d-11e7-83f7-796955fa8fb6.png">
