### ISSUE TITLE
Correctly flip health/exp/mana bars for RTL languages

### ISSUE THREAD

**Issue by phillipthelen** [HabitRPG/habitica-ios#371]
The app mostly renders things correctly for RTL languages (currently only the api-v3 branch), but the bars for health, experience and mana stay the same and are not flipped like the rest of the app.

Possible solutions are to either change them to use a xib file with autolayout (since that handles the flipping automatically) or adjust the frames when an RTL language is active.

What it currently looks like:

![simulator screen shot 13 may 2016 14 40 04](https://cloud.githubusercontent.com/assets/298062/15248099/9a41475a-1918-11e6-9687-4d5f896f8938.png)

**Comment by phillipthelen** [comment]
The class in question that needs changes is `HRPGLabeledProgressBar`

**Comment by TheCodedSelf** [comment]
Looks to me like this is already fixed?

![image](https://user-images.githubusercontent.com/10298140/66257907-16cf2000-e79f-11e9-966c-c754991b4666.png)
