### ISSUE TITLE
Add auto completing health goals

### ISSUE THREAD

**Issue by phillipthelen** [HabitRPG/habitica-ios#388]
**NOTE: If you are interested in working on this issue, please comment here but do not start any work yet. This is still in discussion.**

Since iOS offers Healthkit as a source for activity data, it would be good for the Habitica app to use this data to automatically check off specific tasks.
## This feature would have to include the following:
- Add dailies that autocomplete on different activity goals (see below for events)
- Change existing dailies to be autocompleting
- Add background mode to the app to check if any of the goals were reached and check off the dailies if needed
- Also add this check to p.e. app launches, in case the app doesn't get enough background time
#### automatically tracked by device
- X Steps
- X km walking/running distance
- X km cycling distance
- X flights of stairs climbed
- X hours of standing in a day (automatic entry only on Apple Watch)
- X kcal active energy (automatic entry only on Apple Watch)
- X minutes of exercise (automatic entry only on Apple Watch)
- X km Wheelchair distance (only available in iOS 10)
- X km Wheelchair pushes (only available in iOS 10)
#### has to be entered by user in specific app
- X minutes of workout
- X "Mindful Minutes"
- X hours of sleep
## Questions that are still open:
- Would this require a feature on the server side to check off dailies for yesterday, to be sure it would always get checked off?
- Should we send a local notification to the user when the goal is achieved and the daily checked off?
- Should the user be allowed to manually check off the daily? (if not, should we also ensure this on the other platforms?)
- Should users be able to create challenges with these dailies?

Feedback on everything is welcome!

**Comment by veeeeeee** [comment]
We have thoughts on how we want to handle these interactionz in the future but closing this for now. Moving forward, please submit requests through the feedback form: https://forms.gle/Fa6oztkDsbzLqSvE9. This will help us organize all the requests when we’re thinking about next steps. Thanks!
