### ISSUE TITLE
New Tutorial Popups Needed

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica-ios#392]
We need a Justin Tutorial popup for the Inbox and for the Mount Page. Suggested text is as follows (feedback welcome):

INBOX

This is where you can read and reply to private messages! You can also message people from their profiles. 

MOUNTS

Grow mounts by feeding or saddling pets so that your avatar can ride them!

**Comment by saraolson** [comment]
Since we're adding a tutorial step for the stat allocation, figured i'd bundle this in too.
