### ISSUE TITLE
Some users not displayed as being in a party although they are

### ISSUE THREAD

**Issue by phillipthelen** [HabitRPG/habitica-ios#395]
The iOS displayes the party creation page for some users although they already are in a party.

**Comment by claudinec** [comment]
I have just observed this in the last few days; party view used to work fine but not now.

App version: 1.8.1 (198)
iOS version: 10.3.2 (14F89)

**Comment by vIiRuS** [comment]
As far as I can tell this happens when the app has the user stored twice locally. It should be fixed by using the "Clear Cache" option in the apps settings.
