### ISSUE TITLE
Add .rubyversion file

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitica-ios#400]
Readme suggests using rvm or rbenv, but doesn't specify the preferred ruby version. Some gems require at least 2.2.2, so it should be at least that.

**Comment by jmoody** [comment]
The correct name is `.ruby-version` which is respected by rbenv and rvm.  Sorry for the drive by comment!  I am sure the title is just a typo.  This also helps in CI!

**Comment by crookedneighbor** [comment]
:+1:
