### ISSUE TITLE
FTUE interrupted - customization + tutorial skipped

### ISSUE THREAD

**Issue by artofmrdicks** [HabitRPG/habitica-ios#402]
iOS: 8.3
UID: 52ccd1aa-6975-4382-8979-09e99fc31d97

Installed Habitica to join my wife. Launched FTUE - was confused about all the ponytails and flowers and thought I had accidentally selected female in a previous option so I force closed the app to reset. When relaunched app avatar was selected and FTUE experience was completely skipped. 

Now I need to look up wiki's and videos to learn how to use this app instead of the designed FTUE/tutorial.  Habits, Dailies and To-do's are all blank instead of being pre-filled.

**Comment by vIiRuS** [comment]
Just for the record: Habitica does not have a gender selection and all customization options are available. Your avatar has the gender you choose. So there was no step skipped/missed.

**Comment by artofmrdicks** [comment]
When I reopened the app it had selected whatever options I had previewed before turning it off without me confirming them. Regardless of there being an gender option (I later looked up on the wiki that there isn't one) when I relaunched the app it should have thrown me back into the FTUE flow not forced to the end of it. So there was a step missed/skipped.

**Comment by saraolson** [comment]
I agree that if a user doesn't complete the initial setup itd be nice to restart the app within that screen again, but would like to confirm this is still an issue after the redo of the initial character setup?
