### ISSUE TITLE
Feature Request: Widget

### ISSUE THREAD

**Issue by lonelyclaud** [HabitRPG/habitica-ios#405]
I'd love to see some kind of widget implemented for lockscreen and homescreen, that allow us to quickly check upcoming todos and maybe mark any dailies as completed :)

**Comment by quaestor** [comment]
Would be perfect for adding a todo quickly.

**Comment by spageetman** [comment]
This was one of the first things I checked and I was kinda surprised that this wasn’t already a thing plz do it

**Comment by veeeeeee** [comment]
We have thoughts on how we want to handle this but closing the issue for now. Moving forward, please submit requests through the feedback form: https://forms.gle/Fa6oztkDsbzLqSvE9. This will help us organize all the requests when we’re thinking about next steps. Thanks!
