### ISSUE TITLE
Food received in Enchanted Armoire is not visible when feeding pets

### ISSUE THREAD

**Issue by mbillimoria** [HabitRPG/habitica-ios#407]
Steps to reproduce:
1.) On the iPad app go to rewards and choose Enchanted Armoire
2.) Keep trying until you find some food
3.) Select Menu -> Pets
4.) Choose a Pet and select 'Feed'
5.) Note that the Food you just earned is not present

Expected Behavior:
- The food received from the Armoire drop should be available to use on a pet

Actual Result:
- The food is not present

Workaround:
- You can close/kill the Habitica App and restart it and the missing food will then be present.

My user ID is
872ce1cd-cc92-4f3c-abaa-f037744a8317

**Comment by vIiRuS** [comment]
Note that refreshing the apps data (using pull to refresh on p.e. a task list) should be a sufficient workaround

**Comment by mbillimoria** [comment]
Tested that and you are correct that is a workaround. That being said it would make more sense if a refresh occurs when you press 'Feed'. :-)
