### ISSUE TITLE
App Crashing when Info Button Tapped

### ISSUE THREAD

**Issue by sdale28** [HabitRPG/habitica-ios#414]
Hi there. I just reached level 10 (thereby enabling me to choose a class). When I go to Menu > Select Class a question mark appears in the top right hand corner of the app (which the tip guy said would tell me more about classes). If I tap that Question button, the app immediately crashes. 

User-ID: 8fe24168-e547-4f24-a46e-2dddc0266ca2

Cheers!

**Comment by vIiRuS** [comment]
This is fixed with 229390fe2d5f9ea2096dbf712a115dbf8a866e9c. The update containing the fix is already submitted to apple and will be released as soon as it is reviewed.

**Comment by sdale28** [comment]
Great. Thanks!
