### ISSUE TITLE
Development setup instructions incomplete/unclear

### ISSUE THREAD

**Issue by kalmduck** [HabitRPG/habitica-ios#416]
Following the instructions from the README for setting up cocoapods, when I do 

    pod install

I"m presented with a request for a "key for GoogleClient".  Is it documented somewhere what the expected keys are for GoogleClient, GoogleRedirectUrl, and AmplitudeApiKey?

I wanted to poke around at some issues, but I'm running into this roadblock just getting things setup.

**Comment by vIiRuS** [comment]
the keys that are prompted can be left empty for a development setup.

**Comment by kalmduck** [comment]
Ok.  closing
