### ISSUE TITLE
No way to review Community Guidelines if you've already agreed to them

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica-ios#417]
If a user has accepted the Community Guidelines, there's no way within the app to return to and review them, unless a direct link is provided somewhere in chat. It'd make sense to have a way of bringing the Guidelines screen back up via "Help & FAQ" or "About", or even somewhere on the social screens.

**Comment by saraolson** [comment]
This should be fixed when we get tavern designs in
