### ISSUE TITLE
No Gem-Spending warning when changing class

### ISSUE THREAD

**Issue by Knightress** [HabitRPG/habitica-ios#424]
I accidentally tapped the 'Change Class' button on my Settings menu, and an 'Are You Sure You Want To Spend 3 Gems' message did not appear, and the gems where instantly spent. I didn't change my class (when I saw the menu, I exited the app, and when I went on the website. I opted out,) and I was previously a Warrior. My User ID is a2343741-eda1-4837-8d8a-73bd82c29900. Is there any possibe way I could get my class restored and my Gems back?

**Comment by Alys** [comment]
@Knightress I've given you three gems. You can change your class on the website at User > Stats. Sorry about the trouble!

For any dev who wants to work on adding a warning, here's the Android version of this issue: https://github.com/HabitRPG/habitica-android/issues/524
In brief, there's a warning about the cost, and a warning that you'll no longer be able to buy gear from your previous class, and after the class change there's a confirmation and an explanation of where you can go to change your gear.
