### ISSUE TITLE
Party Members Appearing Twice in List

### ISSUE THREAD

**Issue by smp** [HabitRPG/habitica-ios#426]
# Description

While viewing the party list on iPhone, often there is a duplicate of one party member in the list.

Screenshot below, note that some names were removed by me to protect the confidentiality of party members using their IRL names in-game.

![img_5211](https://cloud.githubusercontent.com/assets/128744/21578579/bc91dfee-cf3a-11e6-9ee5-14944d6ccbcb.PNG)

# Version
iOS: 10.2 (14C92)
App: 1.6.5

**Comment by greay** [comment]
I'm in a 2-person party & sometimes there's up to 3 duplicates at once
