### ISSUE TITLE
Equipment count in enchanted armoire does not update on iPad

### ISSUE THREAD

**Issue by mbillimoria** [HabitRPG/habitica-ios#430]
When you obtain a new piece of equipment in the Armoire the number of pieces left does not update.

Steps to reproduce
1.) Go to the Enchanted Armoire in Rewards
2.) Check that there are items remaining to find (item count is >0)
3.) Tap on the '100' coins to use the Armoire until you find a rare piece of Armoire
4.) Note that the Item count does not reduce even if you refresh the screen by scolding down to force a refresh

Expected behavior
When you receive a new piece of rare Armoire the item count should immediately drop by 1 and display correctly

Workaround
You can leave the Rewards tab and go to another tab and then go back to the Rewards tab and the item count will be correct

**Comment by AmberShards** [comment]
I've also noticed this on my iPhone, iOS 10.2.1.
