### ISSUE TITLE
Missing properties in HabiticaKeys class

### ISSUE THREAD

**Issue by schomes** [HabitRPG/habitica-ios#432]
I recently forked this repository and have made no changes to the code. There seem to be errors present in the code that cause the build to fail. 

A lot of errors seem to be related to attributes not present in the `HabiticaKeys` class: 

`/HRPGGemViewController.m:119:40: Property 'seedsDevApiKey' not found on object of type 'HabiticaKeys *'`

`/HRPGGemViewController.m:120:42: Property 'seedsDevGemsInterstitial' not found on object of type 'HabiticaKeys *'`

`/HRPGGemViewController.m:121:43: Property 'seedsDevShareInterstitial' not found on object of type 'HabiticaKeys *'`

The errors occur on these lines in `HRPGGemViewController.m`:

```
#ifdef DEBUG
    [[Seeds sharedInstance] start:keys.seedsDevApiKey withHost:@"https://dash.playseeds.com"];
    self.seedsGemsInterstitialKey = keys.seedsDevGemsInterstitial;
    self.seedsShareInterstitialKey = keys.seedsDevShareInterstitial;
#else
    [[Seeds sharedInstance] start:keys.seedsReleaseApiKey withHost:@"https://dash.playseeds.com"];
    self.seedsGemsInterstitialKey = keys.seedsReleaseGemsInterstitial;
    self.seedsShareInterstitialKey = keys.seedsReleaseShareInterstitial;
#endif
```

What is an appropriate/recommended action for me to take so that I can build the project? I hesitate to add these properties to the `HabiticaKeys` class myself.

**Comment by vIiRuS** [comment]
Sorry for that.
If you run `pod install` again, you should now be able to set the values to a random value and get it to compile.
