### ISSUE TITLE
Party chat notifications

### ISSUE THREAD

**Issue by migue1s** [HabitRPG/habitica-ios#439]
After joining a party and chatting, push notifications aren't being received when others send a message. As far as I can tell only local notifications are being displayed (the reminder to check off daily tasks for example)

**Comment by vIiRuS** [comment]
The app supports push notifications for other things (like wuest
invitationa and inbox messages), but chat messages currently aren't
aupported server side.

-- 
Phillip Thelen

**Comment by saraolson** [comment]
This can hopefully be added when we get around to improving the unique username system
