### ISSUE TITLE
Special pets cannot be fed

### ISSUE THREAD

**Issue by bleepnik** [HabitRPG/habitica-ios#440]
I thought initially that this was related to #397, or even the same thing, but now I'm not so sure. That issue talks about egg quest pets being able to be fed but not having a growth bar. The issue I'm experiencing is that special pets, such as eggs hatched with the cupid potion, cannot be fed. When I tap the pet, I'm only given the option to equip it, not feed it.

I learned only today from a friend that they can be fed, as she was trying to decide which of her cupid pets she should help grow into a mount. Wait, what?, I said, I didn't know you could feed them! Apparently you can, but only on the website. Having lost so much time, I hurriedly stockpiled cupid potions so I can keep at it after the 28th. =)

iOS 10.2.1, Habitica 1.6.5 (176)

**Comment by vIiRuS** [comment]
This issue will be fixed with the next update, that is currently in review by apple
