### ISSUE TITLE
quest boss health is rounded down and health bar is invisible when < 1

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-ios#442]
As reported in [rounding inconsistencies - Issue #8368 · HabitRPG/habitica](https://github.com/HabitRPG/habitica/issues/8368), on the iOS app a boss's health is rounded down. For consistency with the website, it should be rounded up. Rounding up gives the users a more accurate view of the quest progress (they won't be misled into thinking they need to do less damage than is actually needed to kill the boss).

Rounding up will also avoid a problem where the boss's health bar is invisible when the health is less than 1. The screenshot below was taken when the boss had 0.17 HP. You can see that the health bar does not appear. The quest is still active though as confirmed by the second screenshot below showing the abort button and by me looking at the quest's data in the database.

![image](https://cloud.githubusercontent.com/assets/1495809/24067924/8eed7adc-0bce-11e7-9cac-3582e5524252.png)

![image](https://cloud.githubusercontent.com/assets/1495809/24067927/9b36080e-0bce-11e7-911b-2c847f0684c7.png)

**Comment by saraolson** [comment]
Adding this to when we work on world boss stuff so we can have an accurate hp bar
