### ISSUE TITLE
viewing the profile for a system chat message gives "Invalid parameter request" error

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-ios#443]
In party chat, if you tap a system message (e.g., a quest damage message) and select "Profile", it opens an empty profile with error message "Invalid parameter request".

This might be best fixed by not showing the "Profile" option on system messages. On the website, these messages don't have any way for clicking to see the profile.

Two examples of system messages are below. The way to identify all system messages is by looking for the `uuid` being set to `system`.

This is low priority.

```
        {
            "id": "b9e5c455-8f05-4f13-b32b-7e518a11349e",
            "text": "`Alys attacks Push-and-Pull Peacock for 395.5 damage.` `Push-and-Pull Peacock attacks party for 1.4 damage.`",
            "timestamp": 1489853607553,
            "likes": {},
            "flags": {},
            "flagCount": 0,
            "uuid": "system"
        },
        {
            "id": "b32b98f6-7182-4994-9cb4-a8e30f5aefdf",
            "text": "`Alys casts Tools of the Trade for the party.`",
            "timestamp": 1489164810560,
            "likes": {},
            "flags": {},
            "flagCount": 0,
            "uuid": "system"
        },
```

**Comment by Ieahleen** [comment]
an other thing that I think it's related to this: tapping on a system message and then Reply, the answer is precompiled with a "@(null)" (instead of a, for example, "@Alys")
