### ISSUE TITLE
wrong food preference notification when feeding Premium pets with any food (Magic Potion, Royal Purple pets)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-ios#445]
When you feed a premium pet (a Magic Potion pet or Royal Purple pet), you see the `messageDontEnjoyFood` message ("[pet name] eats the [food] but doesn't seem to enjoy it.").

You should see the `messageLikesFood` message ("[pet name] really likes the [food]!") because all premium pets enjoy all foods.

**Comment by ronlipke** [comment]
👍
