### ISSUE TITLE
iOS feature of sending PM with user ID shows user profiles without display name

### ISSUE THREAD

**Issue by Ieahleen** [HabitRPG/habitica-ios#446]
If I use the feature of the iOS of sending a message using the user ID I can open profiles without the display name displayed: to reproduce, Inbox->(paper and pencil icon on the upper right corner)->Paste the UUID->Done->It opens the chat (without display name on the upper part of the screen)->Tapping on "Profile" in the upper corner it opens a profile without display name displayed"
[chat without display name](https://drive.google.com/open?id=0B213ebNsVd4TVENpaXE3eGQtV28)
[profile without display name](https://drive.google.com/open?id=0B213ebNsVd4TLXgtNGN0UkVtY2s)

**Comment by chzylee** [comment]
Hey can I pick this up? I'm a new contributor looking for a way to begin contributing. I was able to reproduce the issue myself. I can look through the code for the issue and begin work if someone can give me a starting point (and, of course, permission to pick this up).

**Comment by phillipthelen** [comment]
Feel free to work on it!

As a starting point, the viewcontroller for the user profile can be found
here:
https://github.com/HabitRPG/habitica-ios/blob/develop/HabitRPG/TableViewController/HRPGUserProfileViewController.m

If you need any other assistance, let me know!

-- 
Phillip Thelen
Sent with Airmail

**Comment by chzylee** [comment]
Will do. thanks for the lead
