### ISSUE TITLE
cancelled subscriptions are displayed as if they are still active

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-ios#448]
When a subscription has been cancelled but the termination date has not yet arrived, the app displays the subscription as if it were not cancelled (see screenshot below). This could cause a user to not realise their benefits would run out (and they'd lose their consecutive month count), and it prevents them from being able to resubscribe immediately.

![image](https://cloud.githubusercontent.com/assets/1495809/24319627/2cd1cd40-116d-11e7-8e68-ee04f7af05cb.png)

For reference, here is how the same subscription is displayed on the website:

![image](https://cloud.githubusercontent.com/assets/1495809/24319629/3f1f32d0-116d-11e7-9148-800967b46580.png)

And here's the data for that particular subscription from the database, as proof that it has been cancelled:
```
	"purchased.plan": {
		"customerId": -----------------
		"dateTerminated": "2018-09-02T00:00:00.000Z",
		"dateUpdated": "2017-03-01T07:11:20.175Z",
		"dateCreated": "2017-02-27T17:21:59.978Z",
		"owner": -----------------
		"paymentMethod": "Paypal",
		"planId": "basic_12mo",
		"consecutive": {
			"trinkets": 3,
			"gemCapExtra": 25,
			"offset": 18,
			"count": 3
		},
		"mysteryItems": [],
		"gemsBought": 50,
		"extraMonths": 0,
		"quantity": 1
	}
```

**Comment by saraolson** [comment]
Sounds like this needs a little bit of design work to clarify the in-between state. I'll work on that then when its done add the help wanted label again
