### ISSUE TITLE
Wintery Skins are mixed in with Basic Skins

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-ios#452]
Under Customize Avatar, the Wintery Skins are mixed in with the Basic Skins (instead of being separate as for the other skin types):

![image](https://cloud.githubusercontent.com/assets/1495809/24328269/3e91f2e2-1228-11e7-9968-34b79bd8cd23.png)

----

The website is correct:

![image](https://cloud.githubusercontent.com/assets/1495809/24328270/5087c8dc-1228-11e7-8c02-0d15e851dd67.png)

![image](https://cloud.githubusercontent.com/assets/1495809/24328273/5a4ae5b6-1228-11e7-9b3d-11a4fa490ab7.png)

----

The Android app also has this bug: https://github.com/HabitRPG/habitica-android/issues/733

**Comment by Alys** [comment]
Also when trying to equip a Wintery Skin, an error occurs:
"Must purchase {skin name} to set it on preferences.skin"
The player who reported this (Il Mago, c073342f-4a65-4a13-9ffd-9e7fa5410d6b) does own the Wintery Skins.

![image](https://cloud.githubusercontent.com/assets/1495809/24328323/d040e2b0-1229-11e7-8464-43d37876a3a4.png)

**Comment by Alys** [comment]
Might be fixed by this PR when it goes live: https://github.com/HabitRPG/habitica/pull/8645

**Comment by saraolson** [comment]
Can anyone test this to see if it's been fixed?

**Comment by majestic-owl448** [comment]
Now the skins have no division, they are all mixed together! As of 1.11.3 (253) at least
