### ISSUE TITLE
tapping on Done on the Gems&Subscription page brings to the habit page

### ISSUE THREAD

**Issue by Ieahleen** [HabitRPG/habitica-ios#453]
closing the Gems&Subscription page (tapping on done) brings to the habit page not to the Menu like everything else

**Comment by saraolson** [comment]
So to clarify, the expectation is to see the the last place you were at when you opened the gem/subscription page, correct? I'm assuming you opened from menu, not from tapping the gem on the habits page.

**Comment by Ieahleen** [comment]
The behaviour now is correct, this was a bug for a previous version that
was never closed I imagine.

2017-11-28 15:41 GMT+01:00 Sara Olson <notifications@github.com>:

**Comment by majestic-owl448** [comment]
This was a bug from a previous version, now the behaviour opening from the
menu is correct, it returns on the menu when tapping "Done". The issue now
is for all other pages, when clicking on "Done" returns to the habit page.
This happens from all pages I have tried: tavern, guilds, dailies, todos,
rewards...

2017-11-28 15:41 GMT+01:00 Sara Olson <notifications@github.com>:
