### ISSUE TITLE
The Shiny Seed effect is not visible on Mages

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-ios#460]
As reported in the Report a Bug guild by tricksy.fox (90e5c4f2-d5d9-4472-ab2c-19041ee2218d):

"On iOS I can't see the Shiny Seed-ed Mage in my party. I can see the Rogue and Warrior fine."

**Comment by Ieahleen** [comment]
it's more like Shiny Seeds make mages invisible... 
![file_000](https://cloud.githubusercontent.com/assets/26656284/24837136/5dbabdf6-1d2d-11e7-840d-d3901518adb4.jpeg)
