### ISSUE TITLE
Add transformation buff items to Special section of Items so all users have access

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-ios#461]
Players lower than level 10 can't cast a [transformation buff](http://habitica.wikia.com/wiki/Transformation_Items) (Snowball, Shiny Seed, Seafoam, Spooky Sparkles) because the buff appears in the Skills menu and those players do not have access to the Skills menu.

I'm assuming the same also applies to players who have opted out of the class system but I haven't tested or seen reports of it.

All players should be able to cast the buffs.

~~Unrelated to that, we do often see new players ask about how to obtain skills so I'm wondering if both that and this issue could be best fixed by making the skills menu available to all players all the time, with different content:~~
~~- players less than level 11 see a message saying that their first skill becomes available at level 11~~
~~- players who opted out of the class system see a message that skills are available after they opt back in~~
~~- other players see the skills that their level allows~~
~~- all players see a transformation buff when it's available (but not at other times)~~
**added this as a separate enhancement in #905**

The Android version of this buff is at https://github.com/HabitRPG/habitica-android/issues/740

**Comment by saraolson** [comment]
Yeah this definitely needs some ux work, adding the design tag

**Comment by saraolson** [comment]
for a stopgap, i'd like to add those items to the 'Special' section of a user's inventory and allow use from there. we'd still allow use from skills as its slightly more convenient, but ive seen ppl buy transformation items and go to their items expecting them to be there but they arent.

**Comment by saraolson** [comment]
i wouldnt be against returning to the skills enhancements you listed, @Alys, adding extra messaging to explain what will be available in the future and when. Can make another issue for that enhancement, bc it will probably have to come later due to being a little more involved.
