### ISSUE TITLE
'HabiticaKeys' has no member 'itunesSharedSecret'

### ISSUE THREAD

**Issue by schomes** [HabitRPG/habitica-ios#462]
I'm getting this compilation error:

`.../SubscriptionViewController.swift:25:30: Value of type 'HabiticaKeys' has no member 'itunesSharedSecret'`

The line the error occurs on is in `SubscriptionViewController.swift`:
`let itunesSharedSecret = HabiticaKeys().itunesSharedSecret`

Looking at the interface of `HabiticaKeys`, I only see 3 properties (from `/Pods/CocoaPodsKeys/HabiticaKeys.h`):
`@property (readonly) NSString *googleClient;`
`@property (readonly) NSString *googleRedirectUrl;`
`@property (readonly) NSString *amplitudeApiKey;`

During the `pod install` prompt for `cocoapods-keys`, I gave random values. 

Am I missing a step, or is this a known issue?

**Comment by vIiRuS** [comment]
When did you run the pod install command the last time? There are some new
keys that were added later. If you run the pod install command again, it
should prompt for those.

-- 
Phillip Thelen
Sent with Airmail

**Comment by schomes** [comment]
Running `pod install` again fixed this issue. However, in `SubscriptionViewController` (as well as other files) I got an error that `itunesSharedSecret()` is not a function (it is a string). Xcode prompted to delete the parentheses which fixed the issue. I can now successfully build/run the app. 

This is the line before deleting the parentheses on `itunesSharedSecret()`:

`SwiftyStoreKit.verifyReceipt(using: self.appleValidator, password: self.itunesSharedSecret()) { result in
...
...
`
