### ISSUE TITLE
iOS: app crashes when trying to add a reminder to a daily task

### ISSUE THREAD

**Issue by mareinna** [HabitRPG/habitica-ios#464]
### General Info
  * UUID: 4edd4865-3049-414b-a326-9747b3385ad8
  * Browser: iOS app v 1.7.2 (189)
  * OS: iOS for iPhone v 9.3.4

### Description
[//]: # Every time I try to add a reminder to a daily task in the iOS app, the app freezes, then crashes, and the reminder does not get saved. Posted to the "Report a Bug" guild, was asked to try uninstalling/reinstalling the app. Did that, it had no effect, problem persists. Old reminders are still active and working fine, I just can't save any new ones.

**Comment by vIiRuS** [comment]
This is an issue with iOS 8 and 9. Updating to iOS 10 resolves the issue. I'll also add a fix for this to make it work on older OS versions again in the next update.

**Comment by mareinna** [comment]
Thank you! I can't update the iOS for unrelated reasons. Do you know approximately when the next update will be?

**Comment by vIiRuS** [comment]
We will release the next update within the next few days.
