### ISSUE TITLE
iOS Hasn't Built Successfully in a Month

### ISSUE THREAD

**Issue by BennyHarv3** [HabitRPG/habitica-ios#466]
https://travis-ci.org/HabitRPG/habitica-ios

Looks like there is already a pull request to try and resolve this, but it's a month old.

**Comment by vIiRuS** [comment]
Yes. Unfortunately our resources are limited and I had to focus my work on
the android version of the app in the pst weeks. I'll get to mering in the
pr later this week

-- 
Phillip Thelen
Sent with Airmail

**Comment by vIiRuS** [comment]
Looks like there is still some weird issue where the simulator doesn't start correctly. If anybody has experience with fixing something like this, assistance would be greatly appreciated. Unfortunately I can't seem to figure out why the issue is ocurring on travis at the moment.

**Comment by BennyHarv3** [comment]
I'll take a stab at it over the weekend. I don't know Travis very well, but iOS build errors due to simulator problems are my bread and butter.

**Comment by BennyHarv3** [comment]
I didn't get around to this this past weekend, unfortunately. I'll keep trying to squeeze it in, but if someone finds time, that'd be cool.

**Comment by BennyHarv3** [comment]
So here's what I can find so far for build 58. Unfortunately, my Apple Developer account has lapsed, and I have to check with my wife before renewing (yay money), so I can't test locally.
- The test-without-building line for the iOS 10.1 target is definitely failing. I'm not entirely sure why, though; looks like HabiticaTests.TaskRepeatablesSummaryInteractorTests.setUp () -> () + 34 might be the culprit.
  - Since we're building with iOS 10.2, we could change our test target, and it may be fixed. It seems to be working for the older targets (unless there is some magic I missed).
  - Alternatively, we could try running them locally to see if there's something in particular.
- The older targets for testing, iOS 8.4 and 9.3, seem to be building and testing fine (there are some false positives about halfway through the log, but it doesn't seem to affect the outcome). However, HabitRPG/habitica-ios/Pods/CocoaPodsKeys/HabiticaKeys.m is getting modified during either the build or the testing, and Travis wants to kick off another build because of the change and then fails to do so.
  - I haven't looked into what is changing the file.
  - These should be fine.

So I think we're technically building just fine, just failing a whole bunch from the various test runs.

**Comment by asbhat** [comment]
I was poking around a little bit and started getting [travis errors](https://travis-ci.org/asbhat/habitica-ios/builds/438437127) from the FunkyNetwork pod, which is failing its build as well apparently: https://travis-ci.org/schrockblock/funky-network

**Comment by revolter** [comment]
It builds ok for me.

**Comment by BennyHarv3** [comment]
I'll close the issue then; this is nearly a year old.
