### ISSUE TITLE
message posted to Tavern containing banned words disappears (can't be edited); notification can't be seen in full

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-ios#469]
On the website, when you try to post a message to the Tavern with one of the [banned words](https://github.com/HabitRPG/habitica/pull/8197) in it, you're notified that your message can't be posted and it remains in the message entry box for you to edit it.

On the iOS app, you see the notification but your message is removed, meaning that you have to type it from scratch. The ideal behaviour is that the message remains for editing.

Also I've seen a report that the notification can't be read in full:
"there is the usual red [notification] above but you can see it only in part and it's too fast to read even that small part"
The notification should be visible in full and should remain until the user clicks an "ok" button or similar.

**Comment by saraolson** [comment]
adding this to 2.1 with any other chat updates
