### ISSUE TITLE
Task attributes are displayed even if the point allocation method is not "Distribute points based on task activity"

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-ios#473]
In the Report a Bug guild, Olio Lento (c1692c72-6dfb-495c-b4aa-741266a1f6fa) wrote: 
"I ticked User —> Stats —> Character Build —> Automatic Allocation to see possible options. I then unticked "Automatic Allocation", but now when I add a task in iOS application, it has the “Attributes” selector."

I think this is the same bug as reported for the Android app: https://github.com/HabitRPG/habitica-android/issues/784 . That issue contains technical details which might be applicable to iOS as well.

**Comment by saraolson** [comment]
Adding to 1.12 since we're dealing with stat allocation
