### ISSUE TITLE
Setting dev environment

### ISSUE THREAD

**Issue by fiuzaB** [HabitRPG/habitica-ios#474]
Hello everyone,

I didn't want to create this "issue" but I'm clueless on how to proceed with this problem. 

I was setting up my dev environment to start analyzing some issues we have here  and due to four errors (all seems related) my project isn't building.  

See the ss below 
![screen shot 2017-06-22 at 20 37 56](https://user-images.githubusercontent.com/11810770/27460536-b95b4544-578a-11e7-929b-dee91f55d129.png)

The error seems silly, so I imagine I'm probably doing something wrong.

**Comment by vIiRuS** [comment]
I'm not entirely sure what causes this issue. Sometimes the keys pod seems to use properties (accessed without `()`) and sometimes functions (accessed with `()`).
Can you check which version of the `cocoapods-keys` pod you are using?
In theory the fix in your case would be to remove the `()` at the places where it complains, but those changes should not be committed then.

**Comment by fiuzaB** [comment]
It's 1.0.0 . Yep, it works if I change the code as suggested. The strange thing is that I didn't find anyone with the same issue. Pretty weird.

Well, I'll just have to pay double attention when doing commits.
