### ISSUE TITLE
iOS app keeps prompting me to select a class. 

### ISSUE THREAD

**Issue by MercuryChaos** [HabitRPG/habitica-ios#475]
Whenever I go into the menu to cast a spell on my iPhone, I see the "Select Class" menu option instead of my spells. Sometimes I have to press the option I want and go through the confirmation dialog two or three times before it sticks, and sometimes it never does and I have to close and re-open the app and make the selection again. In any case it never seems to be permanent - at some point I'll open the app and go to cast a spell and it'll tell me to select my class again. This only happens in the iOS app (on my iPhone 5s; I don't use any other iOS devices.) It's never happened on the desktop site.

**Comment by saraolson** [comment]
Since we already have a few issues around class selection, adding this bug to 1.12 in case we can fix it with the other weird behaviors.
