### ISSUE TITLE
task attributes have old names (physical, mental, social, other)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-ios#476]
When you edit a task in the app, the Attributes drop-down menu contains the old names for the attributes (e.g., Physical) instead of the names we use now on the website (Strength, etc).

Physical = Strength
Mental = Intelligence
Social = Constitution
Other = Perception

_(I had thought we already had this recorded so this might be a duplicate. I can't find the old one though. Android version of this bug: https://github.com/HabitRPG/habitica-android/issues/796)_

**Comment by jaclyn9189** [comment]
Has anyone begun working on this?

**Comment by vIiRuS** [comment]
Nope. Feel free to tackle it!

**Comment by thatrobotdev** [comment]
@vIiRuS I would love to do my first PR on a major repo! I was wondering what file I could edit to achieve this! :D

**Comment by saraolson** [comment]
Adding to 1.12 because we're dealing with stat allocation, if someone's currently in the middle of this please let us know!

**Comment by fiuzaB** [comment]
I'll give it a try.
