### ISSUE TITLE
"Account Details" screen shows profile name not login name

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-ios#477]
In the Account Details screen where it says "Login name" it shows `profile.name` (the name displayed on their avatar).  It should show `auth.local.username`.

_This was reported by Il Mago Giallo (c073342f-4a65-4a13-9ffd-9e7fa5410d6b) in the Report a Bug guild._

**Comment by saraolson** [comment]
Adding to 1.12 since we're implementing login name and profile name editing.
