### ISSUE TITLE
Storyboard uses "Automatic Preferred Max Layout Width", which is unavailable in iOS 7

### ISSUE THREAD

**Issue by Shadallark** [HabitRPG/habitica-ios#95]
While working in XCode on this project I have noticed that there is a warning listed that the "Automatic Preferred Max Layout" code is not available prior to iOS 8.  If we want to make the app iOS 7 capable we will want to find other code to use there.  If we are fine having the app be iOS 8 or better than this Issue can be closed.

**Comment by vIiRuS** [comment]
As we also target iOS 7 already, we definitely don't want this warning. Must have missed it before.
